version: "3"
services:
  react-app:
    image: react-app-image
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - ds-phase1
  api-server:
    image: express-api-image
    ports:
      - "5000:5000"
    networks:
      - ds-phase1
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ds-phase1
    volumes:
      - mongodata:/data/db
networks:
  ds-phase1:
    driver: bridge
volumes:
  mongodata:
    driver: local
